name = "homer-attachments"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "attachments"

[[kv_namespaces]]
binding = "BACKUPS"
id = "0e382f1f237f422a829cbc24c4e1cebe"
